name: nix test
on: push
jobs:
    install_nix:
        runs-on: ubuntu-latest
        steps:
        - uses: cachix/install-nix-action
        - name: Print nixpkgs version
          run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'